/**
 * Regenerates every raster and SVG copy of the Vertex brand mark from the
 * single vector definition in `src/lib/brand-mark.ts`.
 *
 *   npx tsx scripts/build-brand-icons.ts
 *
 * Idempotent — byte-for-byte identical output on a re-run, so it is safe to
 * run at any time and produces no spurious git diff. Run it whenever the path
 * data, `MARK_BG`, `MARK_FG` or `MONOGRAM_CAP_RATIO` changes; nothing else
 * regenerates these files, they are committed artefacts.
 *
 * Requires `sharp`, which is not a declared dependency of this project — it
 * arrives with `next` (which uses it for image optimisation) and is therefore
 * always present in node_modules. Same arrangement as Playwright in
 * scripts/capture-projects.mjs: a build-time tool, not a runtime one.
 *
 * ## What gets written, and why each surface differs
 *
 * | File                           | Glyph    | Plate | Consumer                            |
 * | ------------------------------ | -------- | ----- | ----------------------------------- |
 * | `src/app/icon.svg`             | monogram | disc  | `<link rel="icon">` — every browser |
 * | `src/app/favicon.ico`          | monogram | disc  | legacy tabs, bookmarks, Windows     |
 * | `src/app/apple-icon.png`       | wordmark | bleed | iOS home screen (squircle, no alpha)|
 * | `public/icon-192.png`          | wordmark | disc  | manifest `purpose: "any"`           |
 * | `public/icon-512.png`          | wordmark | disc  | manifest `any`, install prompts     |
 * | `public/icon-maskable-512.png` | wordmark | bleed | manifest `maskable` (Android)       |
 * | `public/logo.png`              | wordmark | disc  | schema.org `Organization.logo`      |
 * | `public/logo.svg`              | wordmark | disc  | vector logo for decks, email, press |
 *
 * Both axes are explained in `src/lib/brand-mark.ts`. In short: **plate**
 * because alpha survives on the web but not iOS/Android icon masks, and
 * **glyph** because six letters cannot resolve in a 16px tab (see the comment
 * on the favicon block below for why the split is per-surface, not per-size).
 */

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import { brandMarkSvg, type BrandMarkOptions } from '../src/lib/brand-mark'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** Header stamped onto the two committed .svg files so nobody hand-edits them. */
const GENERATED_NOTE = (opts: Required<Pick<BrandMarkOptions, 'plate' | 'glyph'>>) =>
  `<!-- Generated by scripts/build-brand-icons.ts from src/lib/brand-mark.ts (${opts.glyph} on ${opts.plate}). Do not edit by hand. -->\n`

/** Rasterise the mark at `size` square. Alpha is preserved for `disc`. */
async function png(options: BrandMarkOptions, size: number): Promise<Buffer> {
  const svg = Buffer.from(brandMarkSvg(options))
  return sharp(svg, { density: 384 })
    .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png({ compressionLevel: 9, palette: false })
    .toBuffer()
}

/**
 * Packs PNG payloads into an .ico container.
 *
 * ICO is a 6-byte header, then one 16-byte directory entry per image, then the
 * payloads. Every entry here is a PNG rather than a BMP/DIB — supported since
 * Vista and by every browser that matters, and it keeps the file a tenth of
 * the BMP size. A dimension of 256 or above is encoded as 0.
 */
function ico(images: { size: number; data: Buffer }[]): Buffer {
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // type: 1 = icon
  header.writeUInt16LE(images.length, 4)

  let offset = 6 + images.length * 16
  const entries: Buffer[] = []

  for (const { size, data } of images) {
    const entry = Buffer.alloc(16)
    entry.writeUInt8(size >= 256 ? 0 : size, 0) // width
    entry.writeUInt8(size >= 256 ? 0 : size, 1) // height
    entry.writeUInt8(0, 2) // palette size (0 = truecolour)
    entry.writeUInt8(0, 3) // reserved
    entry.writeUInt16LE(1, 4) // colour planes
    entry.writeUInt16LE(32, 6) // bits per pixel
    entry.writeUInt32LE(data.length, 8)
    entry.writeUInt32LE(offset, 12)
    entries.push(entry)
    offset += data.length
  }

  return Buffer.concat([header, ...entries, ...images.map((i) => i.data)])
}

async function emit(relPath: string, data: Buffer | string) {
  const abs = path.join(ROOT, relPath)
  await mkdir(path.dirname(abs), { recursive: true })
  await writeFile(abs, data)
  const bytes = typeof data === 'string' ? Buffer.byteLength(data) : data.length
  console.log(`  ${relPath.padEnd(32)} ${String(bytes).padStart(7)} bytes`)
}

async function main() {
  console.log('Building brand icons from src/lib/brand-mark.ts\n')

  // --- favicon surfaces (monogram) -----------------------------------------
  // Everything a browser renders at tab scale gets the V, not the wordmark.
  //
  // The split cannot be done per-ICO-frame alone, which is the intuitive fix:
  // Next emits BOTH `<link rel="icon" href="/favicon.ico" sizes="48x48">` and
  // `<link rel="icon" href="/icon.svg" sizes="any">`, and every current browser
  // prefers the SVG. An SVG favicon can respond to `prefers-color-scheme` but
  // has no way to know what size it is being painted at, so it cannot carry
  // both glyphs. Leaving icon.svg on the wordmark would mean the monogram
  // never appeared in Chrome, Firefox or Safari at all.
  //
  // So the line is drawn by surface rather than by pixel size: `icon.svg` and
  // every ICO frame are the monogram; the app/logo assets below keep the
  // wordmark. All three ICO frames match for the same reason — some consumers
  // (Google's SERP favicon among them) fetch the largest frame and downscale
  // it themselves, which would put the unreadable wordmark right back in a
  // 16px slot.
  await emit(
    'src/app/icon.svg',
    GENERATED_NOTE({ plate: 'disc', glyph: 'monogram' }) +
      brandMarkSvg({ plate: 'disc', glyph: 'monogram' }) +
      '\n'
  )

  const icoSizes = [16, 32, 48]
  const icoImages = await Promise.all(
    icoSizes.map(async (size) => ({
      size,
      data: await png({ plate: 'disc', glyph: 'monogram' }, size),
    }))
  )
  await emit('src/app/favicon.ico', ico(icoImages))

  // --- app / logo surfaces (wordmark) --------------------------------------
  // All rendered at 180px or above, where six letters resolve cleanly.
  await emit(
    'public/logo.svg',
    GENERATED_NOTE({ plate: 'disc', glyph: 'wordmark' }) +
      brandMarkSvg({ plate: 'disc', title: 'Vertex Consulting' }) +
      '\n'
  )
  await emit('src/app/apple-icon.png', await png({ plate: 'bleed' }, 180))
  await emit('public/icon-192.png', await png({ plate: 'disc' }, 192))
  await emit('public/icon-512.png', await png({ plate: 'disc' }, 512))
  await emit(
    'public/icon-maskable-512.png',
    await png({ plate: 'bleed' }, 512)
  )
  await emit('public/logo.png', await png({ plate: 'disc' }, 512))

  console.log('\nDone.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
